In [1]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import rc
rc('font', family = 'AppleGothic')


import os
from glob import glob
import json
import warnings

from tqdm import tqdm_notebook
import googlemaps
import folium

from selenium import webdriver
from bs4 import BeautifulSoup
import time
from multiprocessing import pool

In [2]:
population = pd.read_excel('../data/05. population_raw_data.xlsx', header=1)
population

,행정구역(동읍면)별(1),행정구역(동읍면)별(2),항목,계,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,총인구수 (명),51696216.0,3541061.0,3217367.0,3517868,4016272.0,2237345.0,1781229.0,1457890,909130.0,416164.0,141488.0,34844,17562.0
1,NaN,NaN,남자인구수 (명),25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0
2,NaN,NaN,여자인구수 (명),25868622.0,1663934.0,1534379.0,1711114,1971007.0,1164950.0,974549.0,857283,589739.0,302943.0,108793.0,27186,13425.0
3,서울특별시,소계,총인구수 (명),9930616.0,690728.0,751973.0,803507,817467.0,448956.0,350580.0,251961,141649.0,66067.0,24153.0,7058,5475.0
4,NaN,NaN,남자인구수 (명),4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0
5,NaN,NaN,여자인구수 (명),5053827.0,343194.0,379724.0,401149,407391.0,237388.0,186814.0,139885,87616.0,46472.0,18007.0,5158,4069.0
6,NaN,종로구,총인구수 (명),152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,NaN,NaN,남자인구수 (명),75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,NaN,NaN,여자인구수 (명),77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,NaN,중구,총인구수 (명),125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,NaN,NaN,남자인구수 (명),62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,NaN,NaN,여자인구수 (명),63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,NaN,용산구,총인구수 (명),230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,NaN,NaN,남자인구수 (명),111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,NaN,NaN,여자인구수 (명),118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,NaN,성동구,총인구수 (명),299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,NaN,NaN,남자인구수 (명),148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,NaN,NaN,여자인구수 (명),150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,NaN,광진구,총인구수 (명),357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,NaN,NaN,남자인구수 (명),174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,NaN,NaN,여자인구수 (명),182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,NaN,동대문구,총인구수 (명),355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,NaN,NaN,남자인구수 (명),177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,NaN,NaN,여자인구수 (명),177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,NaN,중랑구,총인구수 (명),411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,NaN,NaN,남자인구수 (명),204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,NaN,NaN,여자인구수 (명),206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,NaN,성북구,총인구수 (명),450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,NaN,NaN,남자인구수 (명),219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,NaN,NaN,여자인구수 (명),230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,NaN,고성군,총인구수 (명),54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,NaN,NaN,남자인구수 (명),27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,NaN,NaN,여자인구수 (명),27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,NaN,남해군,총인구수 (명),45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,NaN,NaN,남자인구수 (명),21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,NaN,NaN,여자인구수 (명),23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,NaN,하동군,총인구수 (명),49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,NaN,NaN,남자인구수 (명),24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,NaN,NaN,여자인구수 (명),25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,NaN,산청군,총인구수 (명),36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,NaN,NaN,남자인구수 (명),17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,NaN,NaN,여자인구수 (명),18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,NaN,함양군,총인구수 (명),40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,NaN,NaN,남자인구수 (명),19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,NaN,NaN,여자인구수 (명),20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,NaN,거창군,총인구수 (명),63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,NaN,NaN,남자인구수 (명),30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,NaN,NaN,여자인구수 (명),32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,NaN,합천군,총인구수 (명),48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,NaN,NaN,남자인구수 (명),22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,NaN,NaN,여자인구수 (명),25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
837,제주특별자치도,소계,총인구수 (명),641597.0,43143.0,33430.0,38891,48018.0,26425.0,22119.0,18575,12907.0,5831.0,2346.0,755,231.0
838,NaN,NaN,남자인구수 (명),322545.0,22977.0,17365.0,19777,24432.0,12711.0,10223.0,7552,4231.0,1224.0,329.0,82,26.0
839,NaN,NaN,여자인구수 (명),319052.0,20166.0,16065.0,19114,23586.0,13714.0,11896.0,11023,8676.0,4607.0,2017.0,673,205.0
840,NaN,제주시,총인구수 (명),470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,NaN,NaN,남자인구수 (명),235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,NaN,NaN,여자인구수 (명),234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,NaN,서귀포시,총인구수 (명),170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,NaN,NaN,남자인구수 (명),86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,NaN,NaN,여자인구수 (명),84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

In [3]:
population.rename(columns={'행정구역(동읍면)별(1)':'광역시도', "행정구역(동읍면)별(2)":"시도", '계':"인구수"}, inplace=True)

In [4]:
population.rename(columns={'항목':'구분'}, inplace=True)

In [5]:
population

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,총인구수 (명),51696216.0,3541061.0,3217367.0,3517868,4016272.0,2237345.0,1781229.0,1457890,909130.0,416164.0,141488.0,34844,17562.0
1,NaN,NaN,남자인구수 (명),25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0
2,NaN,NaN,여자인구수 (명),25868622.0,1663934.0,1534379.0,1711114,1971007.0,1164950.0,974549.0,857283,589739.0,302943.0,108793.0,27186,13425.0
3,서울특별시,소계,총인구수 (명),9930616.0,690728.0,751973.0,803507,817467.0,448956.0,350580.0,251961,141649.0,66067.0,24153.0,7058,5475.0
4,NaN,NaN,남자인구수 (명),4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0
5,NaN,NaN,여자인구수 (명),5053827.0,343194.0,379724.0,401149,407391.0,237388.0,186814.0,139885,87616.0,46472.0,18007.0,5158,4069.0
6,NaN,종로구,총인구수 (명),152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,NaN,NaN,남자인구수 (명),75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,NaN,NaN,여자인구수 (명),77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,NaN,중구,총인구수 (명),125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,NaN,NaN,남자인구수 (명),62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,NaN,NaN,여자인구수 (명),63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,NaN,용산구,총인구수 (명),230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,NaN,NaN,남자인구수 (명),111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,NaN,NaN,여자인구수 (명),118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,NaN,성동구,총인구수 (명),299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,NaN,NaN,남자인구수 (명),148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,NaN,NaN,여자인구수 (명),150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,NaN,광진구,총인구수 (명),357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,NaN,NaN,남자인구수 (명),174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,NaN,NaN,여자인구수 (명),182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,NaN,동대문구,총인구수 (명),355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,NaN,NaN,남자인구수 (명),177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,NaN,NaN,여자인구수 (명),177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,NaN,중랑구,총인구수 (명),411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,NaN,NaN,남자인구수 (명),204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,NaN,NaN,여자인구수 (명),206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,NaN,성북구,총인구수 (명),450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,NaN,NaN,남자인구수 (명),219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,NaN,NaN,여자인구수 (명),230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,NaN,고성군,총인구수 (명),54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,NaN,NaN,남자인구수 (명),27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,NaN,NaN,여자인구수 (명),27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,NaN,남해군,총인구수 (명),45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,NaN,NaN,남자인구수 (명),21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,NaN,NaN,여자인구수 (명),23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,NaN,하동군,총인구수 (명),49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,NaN,NaN,남자인구수 (명),24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,NaN,NaN,여자인구수 (명),25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,NaN,산청군,총인구수 (명),36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,NaN,NaN,남자인구수 (명),17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,NaN,NaN,여자인구수 (명),18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,NaN,함양군,총인구수 (명),40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,NaN,NaN,남자인구수 (명),19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,NaN,NaN,여자인구수 (명),20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,NaN,거창군,총인구수 (명),63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,NaN,NaN,남자인구수 (명),30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,NaN,NaN,여자인구수 (명),32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,NaN,합천군,총인구수 (명),48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,NaN,NaN,남자인구수 (명),22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,NaN,NaN,여자인구수 (명),25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
837,제주특별자치도,소계,총인구수 (명),641597.0,43143.0,33430.0,38891,48018.0,26425.0,22119.0,18575,12907.0,5831.0,2346.0,755,231.0
838,NaN,NaN,남자인구수 (명),322545.0,22977.0,17365.0,19777,24432.0,12711.0,10223.0,7552,4231.0,1224.0,329.0,82,26.0
839,NaN,NaN,여자인구수 (명),319052.0,20166.0,16065.0,19114,23586.0,13714.0,11896.0,11023,8676.0,4607.0,2017.0,673,205.0
840,NaN,제주시,총인구수 (명),470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,NaN,NaN,남자인구수 (명),235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,NaN,NaN,여자인구수 (명),234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,NaN,서귀포시,총인구수 (명),170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,NaN,NaN,남자인구수 (명),86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,NaN,NaN,여자인구수 (명),84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

In [6]:
population[population['구분'] == '남자인구수 (명)']

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
1,NaN,NaN,남자인구수 (명),25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0
4,NaN,NaN,남자인구수 (명),4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0
7,NaN,NaN,남자인구수 (명),75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
10,NaN,NaN,남자인구수 (명),62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
13,NaN,NaN,남자인구수 (명),111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
16,NaN,NaN,남자인구수 (명),148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
19,NaN,NaN,남자인구수 (명),174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
22,NaN,NaN,남자인구수 (명),177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
25,NaN,NaN,남자인구수 (명),204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
28,NaN,NaN,남자인구수 (명),219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
31,NaN,NaN,남자인구수 (명),160861.0,11206.0,10737.0,11838,12998.0,8084.0,6836.0,4961,2313.0,731.0,219.0,66,63.0
34,NaN,NaN,남자인구수 (명),171238.0,12666.0,11645.0,12255,12757.0,8073.0,6328.0,4547,2172.0,865.0,240.0,68,25.0
37,NaN,NaN,남자인구수 (명),276333.0,22312.0,17869.0,18458,20799.0,10786.0,8040.0,5815,2928.0,1190.0,335.0,97,72.0
40,NaN,NaN,남자인구수 (명),239183.0,16375.0,15885.0,17908,20205.0,10868.0,8796.0,6563,3163.0,1096.0,331.0,82,52.0
43,NaN,NaN,남자인구수 (명),152510.0,11584.0,12198.0,11779,12022.0,6491.0,5622.0,4409,2266.0,786.0,240.0,88,52.0
46,NaN,NaN,남자인구수 (명),182162.0,12499.0,14694.0,17071,16774.0,6592.0,5667.0,4385,2224.0,871.0,245.0,87,65.0
49,NaN,NaN,남자인구수 (명),236290.0,17983.0,14907.0,16175,17102.0,9542.0,6410.0,4035,1937.0,761.0,228.0,64,34.0
52,NaN,NaN,남자인구수 (명),290478.0,19802.0,21694.0,27022,27611.0,12632.0,8938.0,5372,2631.0,1064.0,341.0,104,55.0
55,NaN,NaN,남자인구수 (명),207667.0,13431.0,14521.0,17738,19226.0,10116.0,7440.0,4719,2150.0,692.0,173.0,44,35.0
58,NaN,NaN,남자인구수 (명),119885.0,8289.0,9789.0,10346,9753.0,5696.0,4284.0,2745,1221.0,390.0,114.0,36,54.0
61,NaN,NaN,남자인구수 (명),185200.0,11516.0,14716.0,17501,16535.0,8530.0,6475.0,4478,2424.0,759.0,253.0,91,63.0
64,NaN,NaN,남자인구수 (명),196267.0,14662.0,17297.0,17786,17357.0,8572.0,6989.0,4882,2382.0,865.0,266.0,79,72.0
67,NaN,NaN,남자인구수 (명),256143.0,19089.0,30096.0,28179,23598.0,11288.0,8945.0,6113,2517.0,807.0,226.0,60,57.0
70,NaN,NaN,남자인구수 (명),214673.0,13935.0,14585.0,16409,18010.0,8638.0,6839.0,4350,2106.0,782.0,307.0,82,54.0
73,NaN,NaN,남자인구수 (명),271604.0,19597.0,19592.0,21817,22470.0,10737.0,8279.0,5087,2384.0,879.0,330.0,104,49.0
76,NaN,NaN,남자인구수 (명),320557.0,22465.0,23330.0,26914,27485.0,13518.0,9284.0,5540,2685.0,1010.0,340.0,93,59.0
79,NaN,NaN,남자인구수 (명),221118.0,15899.0,16073.0,17580,18495.0,10095.0,6983.0,4091,1821.0,720.0,235.0,67,59.0
82,NaN,NaN,남자인구수 (명),1725607.0,127936.0,112087.0,114667,132506.0,90841.0,64984.0,44514,21014.0,6959.0,1840.0,402,340.0
85,NaN,NaN,남자인구수 (명),22174.0,1432.0,1520.0,1480,1502.0,1424.0,1183.0,847,378.0,154.0,51.0,17,15.0
88,NaN,NaN,남자인구수 (명),55469.0,3834.0,3412.0,3197,3723.0,3683.0,2741.0,2039,1037.0,338.0,108.0,36,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,NaN,NaN,남자인구수 (명),16667.0,774.0,600.0,659,818.0,1329.0,1021.0,1048,667.0,254.0,63.0,8,10.0
760,NaN,NaN,남자인구수 (명),25847.0,1527.0,1296.0,1277,1591.0,1501.0,1257.0,1115,664.0,233.0,59.0,11,2.0
763,NaN,NaN,남자인구수 (명),5430.0,317.0,311.0,290,334.0,344.0,259.0,182,117.0,40.0,17.0,3,4.0
766,NaN,NaN,남자인구수 (명),1699219.0,121582.0,97353.0,110068,132603.0,72692.0,50324.0,39052,21428.0,7522.0,1900.0,349,105.0
769,NaN,NaN,남자인구수 (명),540073.0,42428.0,35878.0,37958,42882.0,21127.0,13286.0,9004,4527.0,1499.0,383.0,58,31.0
772,NaN,NaN,남자인구수 (명),128719.0,11369.0,9037.0,9061,9775.0,4765.0,2771.0,1781,995.0,300.0,84.0,12,4.0
775,NaN,NaN,남자인구수 (명),118468.0,10989.0,9480.0,8533,8362.0,2806.0,1383.0,856,450.0,171.0,50.0,6,4.0
778,NaN,NaN,남자인구수 (명),90716.0,6290.0,5423.0,6167,7156.0,5028.0,3420.0,2460,1208.0,471.0,112.0,19,14.0
781,NaN,NaN,남자인구수 (명),106469.0,8041.0,6508.0,6917,8183.0,4976.0,3257.0,2116,951.0,251.0,60.0,10,5.0
784,NaN,NaN,남자인구수 (명),95701.0,5739.0,5430.0,7280,9406.0,3552.0,2455.0,1791,923.0,306.0,77.0,11,4.0
787,NaN,NaN,남자인구수 (명),171855.0,13800.0,10613.0,10440,12409.0,7352.0,5389.0,4021,2015.0,697.0,201.0,50,14.0
790,NaN,NaN,남자인구수 (명),69769.0,4047.0,3182.0,4457,6033.0,3508.0,2326.0,1610,860.0,295.0,55.0,10,7.0
793,NaN,NaN,남자인구수 (명),57698.0,3719.0,2975.0,3453,4434.0,2984.0,2167.0,1812,986.0,310.0,74.0,16,4.0
796,NaN,NaN,남자인구수 (명),267513.0,20568.0,14750.0,16831,22091.0,7845.0,5320.0,3642,1817.0,612.0,139.0,31,13.0
799,NaN,NaN,남자인구수 (명),52992.0,3509.0,2482.0,2668,3065.0,3529.0,2633.0,2045,1275.0,438.0,95.0,18,1.0
802,NaN,NaN,남자인구수 (명),135738.0,8064.0,7789.0,12492,14400.0,3797.0,2177.0,1510,855.0,280.0,80.0,15,5.0
805,NaN,NaN,남자인구수 (명),159503.0,11133.0,9271.0,11111,14131.0,5838.0,4063.0,2819,1491.0,481.0,130.0,19,5.0
808,NaN,NaN,남자인구수 (명),13562.0,700.0,536.0,509,693.0,1010.0,779.0,842,533.0,205.0,60.0,10,0.0
811,NaN,NaN,남자인구수 (명),34819.0,2089.0,1507.0,1755,2384.0,1963.0,1348.0,1199,688.0,231.0,59.0,11,1.0
814,NaN,NaN,남자인구수 (명),31735.0,1922.0,1591.0,1548,1820.0,2174.0,1639.0,1500,876.0,283.0,56.0,12,0.0
817,NaN,NaN,남자인구수 (명),27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
820,NaN,NaN,남자인구수 (명),21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
823,NaN,NaN,남자인구수 (명),24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
826,NaN,NaN,남자인구수 (명),17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
829,NaN,NaN,남자인구수 (명),19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
832,NaN,NaN,남자인구수 (명),30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
835,NaN,NaN,남자인구수 (명),22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
838,NaN,NaN,남자인구수 (명),322545.0,22977.0,17365.0,19777,24432.0,12711.0,10223.0,7552,4231.0,1224.0,329.0,82,26.0
841,NaN,NaN,남자인구수 (명),235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
844,NaN,NaN,남자인구수 (명),86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0

In [7]:
population.loc[population['구분'] == '남자인구수 (명)', '구분'] = '남자'

In [8]:
population

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,총인구수 (명),51696216.0,3541061.0,3217367.0,3517868,4016272.0,2237345.0,1781229.0,1457890,909130.0,416164.0,141488.0,34844,17562.0
1,NaN,NaN,남자,25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0
2,NaN,NaN,여자인구수 (명),25868622.0,1663934.0,1534379.0,1711114,1971007.0,1164950.0,974549.0,857283,589739.0,302943.0,108793.0,27186,13425.0
3,서울특별시,소계,총인구수 (명),9930616.0,690728.0,751973.0,803507,817467.0,448956.0,350580.0,251961,141649.0,66067.0,24153.0,7058,5475.0
4,NaN,NaN,남자,4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0
5,NaN,NaN,여자인구수 (명),5053827.0,343194.0,379724.0,401149,407391.0,237388.0,186814.0,139885,87616.0,46472.0,18007.0,5158,4069.0
6,NaN,종로구,총인구수 (명),152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,NaN,NaN,남자,75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,NaN,NaN,여자인구수 (명),77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,NaN,중구,총인구수 (명),125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,NaN,NaN,남자,62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,NaN,NaN,여자인구수 (명),63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,NaN,용산구,총인구수 (명),230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,NaN,NaN,남자,111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,NaN,NaN,여자인구수 (명),118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,NaN,성동구,총인구수 (명),299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,NaN,NaN,남자,148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,NaN,NaN,여자인구수 (명),150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,NaN,광진구,총인구수 (명),357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,NaN,NaN,남자,174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,NaN,NaN,여자인구수 (명),182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,NaN,동대문구,총인구수 (명),355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,NaN,NaN,남자,177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,NaN,NaN,여자인구수 (명),177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,NaN,중랑구,총인구수 (명),411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,NaN,NaN,남자,204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,NaN,NaN,여자인구수 (명),206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,NaN,성북구,총인구수 (명),450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,NaN,NaN,남자,219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,NaN,NaN,여자인구수 (명),230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,NaN,고성군,총인구수 (명),54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,NaN,NaN,남자,27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,NaN,NaN,여자인구수 (명),27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,NaN,남해군,총인구수 (명),45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,NaN,NaN,남자,21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,NaN,NaN,여자인구수 (명),23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,NaN,하동군,총인구수 (명),49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,NaN,NaN,남자,24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,NaN,NaN,여자인구수 (명),25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,NaN,산청군,총인구수 (명),36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,NaN,NaN,남자,17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,NaN,NaN,여자인구수 (명),18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,NaN,함양군,총인구수 (명),40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,NaN,NaN,남자,19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,NaN,NaN,여자인구수 (명),20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,NaN,거창군,총인구수 (명),63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,NaN,NaN,남자,30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,NaN,NaN,여자인구수 (명),32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,NaN,합천군,총인구수 (명),48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,NaN,NaN,남자,22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,NaN,NaN,여자인구수 (명),25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
837,제주특별자치도,소계,총인구수 (명),641597.0,43143.0,33430.0,38891,48018.0,26425.0,22119.0,18575,12907.0,5831.0,2346.0,755,231.0
838,NaN,NaN,남자,322545.0,22977.0,17365.0,19777,24432.0,12711.0,10223.0,7552,4231.0,1224.0,329.0,82,26.0
839,NaN,NaN,여자인구수 (명),319052.0,20166.0,16065.0,19114,23586.0,13714.0,11896.0,11023,8676.0,4607.0,2017.0,673,205.0
840,NaN,제주시,총인구수 (명),470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,NaN,NaN,남자,235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,NaN,NaN,여자인구수 (명),234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,NaN,서귀포시,총인구수 (명),170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,NaN,NaN,남자,86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,NaN,NaN,여자인구수 (명),84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

In [9]:
population.loc[population['구분'] == '여자인구수 (명)', '구분'] = '여자'

In [10]:
population

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,총인구수 (명),51696216.0,3541061.0,3217367.0,3517868,4016272.0,2237345.0,1781229.0,1457890,909130.0,416164.0,141488.0,34844,17562.0
1,NaN,NaN,남자,25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0
2,NaN,NaN,여자,25868622.0,1663934.0,1534379.0,1711114,1971007.0,1164950.0,974549.0,857283,589739.0,302943.0,108793.0,27186,13425.0
3,서울특별시,소계,총인구수 (명),9930616.0,690728.0,751973.0,803507,817467.0,448956.0,350580.0,251961,141649.0,66067.0,24153.0,7058,5475.0
4,NaN,NaN,남자,4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0
5,NaN,NaN,여자,5053827.0,343194.0,379724.0,401149,407391.0,237388.0,186814.0,139885,87616.0,46472.0,18007.0,5158,4069.0
6,NaN,종로구,총인구수 (명),152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,NaN,NaN,남자,75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,NaN,NaN,여자,77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,NaN,중구,총인구수 (명),125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,NaN,NaN,남자,62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,NaN,NaN,여자,63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,NaN,용산구,총인구수 (명),230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,NaN,NaN,남자,111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,NaN,NaN,여자,118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,NaN,성동구,총인구수 (명),299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,NaN,NaN,남자,148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,NaN,NaN,여자,150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,NaN,광진구,총인구수 (명),357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,NaN,NaN,남자,174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,NaN,NaN,여자,182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,NaN,동대문구,총인구수 (명),355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,NaN,NaN,남자,177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,NaN,NaN,여자,177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,NaN,중랑구,총인구수 (명),411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,NaN,NaN,남자,204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,NaN,NaN,여자,206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,NaN,성북구,총인구수 (명),450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,NaN,NaN,남자,219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,NaN,NaN,여자,230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,NaN,고성군,총인구수 (명),54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,NaN,NaN,남자,27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,NaN,NaN,여자,27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,NaN,남해군,총인구수 (명),45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,NaN,NaN,남자,21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,NaN,NaN,여자,23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,NaN,하동군,총인구수 (명),49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,NaN,NaN,남자,24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,NaN,NaN,여자,25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,NaN,산청군,총인구수 (명),36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,NaN,NaN,남자,17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,NaN,NaN,여자,18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,NaN,함양군,총인구수 (명),40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,NaN,NaN,남자,19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,NaN,NaN,여자,20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,NaN,거창군,총인구수 (명),63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,NaN,NaN,남자,30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,NaN,NaN,여자,32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,NaN,합천군,총인구수 (명),48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,NaN,NaN,남자,22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,NaN,NaN,여자,25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
837,제주특별자치도,소계,총인구수 (명),641597.0,43143.0,33430.0,38891,48018.0,26425.0,22119.0,18575,12907.0,5831.0,2346.0,755,231.0
838,NaN,NaN,남자,322545.0,22977.0,17365.0,19777,24432.0,12711.0,10223.0,7552,4231.0,1224.0,329.0,82,26.0
839,NaN,NaN,여자,319052.0,20166.0,16065.0,19114,23586.0,13714.0,11896.0,11023,8676.0,4607.0,2017.0,673,205.0
840,NaN,제주시,총인구수 (명),470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,NaN,NaN,남자,235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,NaN,NaN,여자,234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,NaN,서귀포시,총인구수 (명),170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,NaN,NaN,남자,86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,NaN,NaN,여자,84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

In [11]:
# 총인구수 (명)

population.loc[population['구분'] == '총인구수 (명)', '구분'] = '총인구'

In [12]:
population

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,총인구,51696216.0,3541061.0,3217367.0,3517868,4016272.0,2237345.0,1781229.0,1457890,909130.0,416164.0,141488.0,34844,17562.0
1,NaN,NaN,남자,25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0
2,NaN,NaN,여자,25868622.0,1663934.0,1534379.0,1711114,1971007.0,1164950.0,974549.0,857283,589739.0,302943.0,108793.0,27186,13425.0
3,서울특별시,소계,총인구,9930616.0,690728.0,751973.0,803507,817467.0,448956.0,350580.0,251961,141649.0,66067.0,24153.0,7058,5475.0
4,NaN,NaN,남자,4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0
5,NaN,NaN,여자,5053827.0,343194.0,379724.0,401149,407391.0,237388.0,186814.0,139885,87616.0,46472.0,18007.0,5158,4069.0
6,NaN,종로구,총인구,152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,NaN,NaN,남자,75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,NaN,NaN,여자,77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,NaN,중구,총인구,125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,NaN,NaN,남자,62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,NaN,NaN,여자,63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,NaN,용산구,총인구,230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,NaN,NaN,남자,111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,NaN,NaN,여자,118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,NaN,성동구,총인구,299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,NaN,NaN,남자,148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,NaN,NaN,여자,150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,NaN,광진구,총인구,357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,NaN,NaN,남자,174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,NaN,NaN,여자,182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,NaN,동대문구,총인구,355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,NaN,NaN,남자,177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,NaN,NaN,여자,177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,NaN,중랑구,총인구,411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,NaN,NaN,남자,204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,NaN,NaN,여자,206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,NaN,성북구,총인구,450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,NaN,NaN,남자,219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,NaN,NaN,여자,230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,NaN,고성군,총인구,54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,NaN,NaN,남자,27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,NaN,NaN,여자,27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,NaN,남해군,총인구,45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,NaN,NaN,남자,21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,NaN,NaN,여자,23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,NaN,하동군,총인구,49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,NaN,NaN,남자,24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,NaN,NaN,여자,25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,NaN,산청군,총인구,36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,NaN,NaN,남자,17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,NaN,NaN,여자,18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,NaN,함양군,총인구,40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,NaN,NaN,남자,19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,NaN,NaN,여자,20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,NaN,거창군,총인구,63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,NaN,NaN,남자,30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,NaN,NaN,여자,32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,NaN,합천군,총인구,48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,NaN,NaN,남자,22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,NaN,NaN,여자,25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
837,제주특별자치도,소계,총인구,641597.0,43143.0,33430.0,38891,48018.0,26425.0,22119.0,18575,12907.0,5831.0,2346.0,755,231.0
838,NaN,NaN,남자,322545.0,22977.0,17365.0,19777,24432.0,12711.0,10223.0,7552,4231.0,1224.0,329.0,82,26.0
839,NaN,NaN,여자,319052.0,20166.0,16065.0,19114,23586.0,13714.0,11896.0,11023,8676.0,4607.0,2017.0,673,205.0
840,NaN,제주시,총인구,470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,NaN,NaN,남자,235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,NaN,NaN,여자,234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,NaN,서귀포시,총인구,170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,NaN,NaN,남자,86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,NaN,NaN,여자,84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

In [13]:
population.fillna(method='pad', inplace=True)

In [14]:
population['20 - 39세'] = population.loc[:,'20 - 24세':'35 - 39세'].apply(lambda x:x.sum(), axis = 1)

In [15]:
population.head()

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+,20 - 39세
0,전국,소계,총인구,51696216.0,3541061.0,3217367.0,3517868,4016272.0,2237345.0,1781229.0,1457890,909130.0,416164.0,141488.0,34844,17562.0,14292568.0
1,전국,소계,남자,25827594.0,1877127.0,1682988.0,1806754,2045265.0,1072395.0,806680.0,600607,319391.0,113221.0,32695.0,7658,4137.0,7412134.0
2,전국,소계,여자,25868622.0,1663934.0,1534379.0,1711114,1971007.0,1164950.0,974549.0,857283,589739.0,302943.0,108793.0,27186,13425.0,6880434.0
3,서울특별시,소계,총인구,9930616.0,690728.0,751973.0,803507,817467.0,448956.0,350580.0,251961,141649.0,66067.0,24153.0,7058,5475.0,3063675.0
4,서울특별시,소계,남자,4876789.0,347534.0,372249.0,402358,410076.0,211568.0,163766.0,112076,54033.0,19595.0,6146.0,1900,1406.0,1532217.0

In [16]:
population['노인'] = population.loc[:,"65 - 69세":"100+"].apply(lambda x: x.sum(), axis = 1)

In [17]:
population = population[population['시도'] != '소계']

In [18]:
pop_pivot = pd.pivot_table(population,index=['광역시도', '시도'],columns=['구분'], values=['인구수','20 - 39세', '노인'])
pop_pivot.to_csv("../data/test1.csv")
pop_pivot

           20 - 39세                           노인                          인구수  \
구분               남자        여자       총인구       남자       여자       총인구        남자
광역시도 시도
강원도  강릉시    26286.0   23098.0   49384.0  15767.0  21912.0   37679.0  106231.0
     고성군     4494.0    2529.0    7023.0   2900.0   4251.0    7151.0   15899.0
     동해시    11511.0    9753.0   21264.0   6392.0   8732.0   15124.0   47166.0
     삼척시     8708.0    7115.0   15823.0   5892.0   8718.0   14610.0   35253.0
     속초시     9956.0    8752.0   18708.0   5139.0   7613.0   12752.0   40288.0
     양구군     4368.0    2481.0    6849.0   1650.0   2458.0    4108.0   12918.0
     양양군     2916.0    2171.0    5087.0   2988.0   3993.0    6981.0   13838.0
     영월군     4025.0    3134.0    7159.0   4215.0   5700.0    9915.0   20652.0
     원주시    45755.0   43164.0   88919.0  17384.0  24862.0   42246.0  167854.0
     인제군     5512.0    3449.0    8961.0   2413.0   3189.0    5602.0   17677.0
     정선군     4138.0    3297.0    7435.0   3831.0   5177.0    9008.0   19975.0
     철원군     7918.0    4714.0   12632.0   3804.0   5308.0    9112.0   25429.0
     춘천시    37173.0   35422.0   72595.0  17259.0  24440.0   41699.0  138251.0
     태백시     5333.0    4643.0    9976.0   3978.0   5288.0    9266.0   23899.0
     평창군     4377.0    3585.0    7962.0   4223.0   5614.0    9837.0   22126.0
     홍천군     7900.0    6258.0   14158.0   6450.0   8483.0   14933.0   35738.0
     화천군     5397.0    2643.0    8040.0   1991.0   2815.0    4806.0   14554.0
     횡성군     4512.0    3789.0    8301.0   4941.0   6382.0   11323.0   23398.0
경기도  가평군     7024.0    5771.0   12795.0   5960.0   7609.0   13569.0   31981.0
     고양시   143723.0  145020.0  288743.0  46866.0  67226.0  114092.0  510923.0
     과천시     8582.0    8315.0   16897.0   3117.0   4618.0    7735.0   31013.0
     광명시    49509.0   47807.0   97316.0  15468.0  21081.0   36549.0  168241.0
     광주시    49690.0   45073.0   94763.0  16061.0  19142.0   35203.0  168345.0
     구리시    27732.0   26941.0   54673.0   8903.0  11720.0   20623.0   96397.0
     군포시    43183.0   41049.0   84232.0  12126.0  16404.0   28530.0  141647.0
     권선구    60291.0   56279.0  116570.0  13234.0  17690.0   30924.0  180766.0
     기흥구    56866.0   58658.0  115524.0  18831.0  24001.0   42832.0  206316.0
     김포시    49921.0   49660.0   99581.0  17847.0  22658.0   40505.0  182597.0
     남양주시   87416.0   86835.0  174251.0  33150.0  42836.0   75986.0  330749.0
     단원구    49620.0   43619.0   93239.0  10430.0  14100.0   24530.0  161915.0
...             ...       ...       ...      ...      ...       ...       ...
충청남도 금산군     5448.0    4454.0    9902.0   6012.0   8594.0   14606.0   27558.0
     논산시    14111.0   11900.0   26011.0  11593.0  16464.0   28057.0   61724.0
     당진시    24970.0   19356.0   44326.0  11765.0  15680.0   27445.0   87388.0
     동남구    38023.0   35222.0   73245.0  12858.0  17329.0   30187.0  131135.0
     보령시    12314.0    9590.0   21904.0   9579.0  13389.0   22968.0   52521.0
     부여군     6822.0    5348.0   12170.0   8575.0  12197.0   20772.0   34837.0
     서북구    63523.0   57966.0  121489.0  11150.0  15664.0   26814.0  182987.0
     서산시    23700.0   19196.0   42896.0  11840.0  16190.0   28030.0   87770.0
     서천군     5219.0    4142.0    9361.0   7221.0  10363.0   17584.0   27539.0
     아산시    47643.0   42296.0   89939.0  14581.0  20486.0   35067.0  155692.0
     예산군     8450.0    6665.0   15115.0   9230.0  12776.0   22006.0   40827.0
     천안시   101546.0   93188.0  194734.0  24008.0  32993.0   57001.0  314122.0
     청양군     3207.0    2410.0    5617.0   4300.0   6029.0   10329.0   16389.0
     태안군     6956.0    5271.0   12227.0   7241.0   9627.0   16868.0   32260.0
     홍성군    11691.0   10428.0   22119.0   8889.0  12426.0   21315.0   49769.0
충청북도 괴산군     3606.0    2726.0    6332.0   4890.0   6702.0   11592.0   19773.0
     단양군     2907.0    2289.0    5196.0   3278.0   4619.0    7897.0   15362.0
     보은군     3097.0    2498.0    5595.0   4165.0   6022.0   10187.0   17093.0
     상당구    23359.0   21071.0   44430.0   9727.0  13849.0   23576.0   86804.0
     서원구    31810.0   29168.0   60978.0   9950.0  14237.0   24187.0  107866.0
     영동군     5369.0    4217.0    9586.0   5564.0   8186.0   13750.0   25248.0
     옥천군     5373.0    4445.0    9818.0   5533.0   7722.0   13255.0   26251.0
     음성군    12684.0   10179.0   22863.0   7301.0   9605.0   16906.0   51372.0
     제천시    16563.0   14279.0   30842.0  10227.0  13904.0   24131.0   68444.0
     증평군     5531.0    4554.0   10085.0   2206.0   3117.0    5323.0   19110.0
     진천군     9391.0    7622.0   17013.0   4731.0   6575.0   11306.0   36387.0
     청원구    32216.0   27805.0   60021.0   8417.0  11914.0   20331.0   97006.0
     청주시   128318.0  115719.0  244037.0  37882.0  53671.0   91553.0  419323.0
     충주시    26600.0   22757.0   49357.0  14407.0  20383.0   34790.0  104877.0
     흥덕구    40933.0   37675.0   78608.0   9788.0  13671.0   23459.0  127647.0


구분               여자        총인구
광역시도 시도
강원도  강릉시   107615.0   213846.0
     고성군    14215.0    30114.0
     동해시    46131.0    93297.0
     삼척시    34346.0    69599.0
     속초시    41505.0    81793.0
     양구군    11092.0    24010.0
     양양군    13380.0    27218.0
     영월군    19421.0    40073.0
     원주시   170125.0   337979.0
     인제군    15043.0    32720.0
     정선군    18743.0    38718.0
     철원군    22584.0    48013.0
     춘천시   142456.0   280707.0
     태백시    23171.0    47070.0
     평창군    21192.0    43318.0
     홍천군    34338.0    70076.0
     화천군    11710.0    26264.0
     횡성군    22593.0    45991.0
경기도  가평군    30467.0    62448.0
     고양시   528761.0  1039684.0
     과천시    32765.0    63778.0
     광명시   171243.0   339484.0
     광주시   159378.0   327723.0
     구리시    97366.0   193763.0
     군포시   143243.0   284890.0
     권선구   177627.0   358393.0
     기흥구   210847.0   417163.0
     김포시   180846.0   363443.0
     남양주시  331405.0   662154.0
     단원구   152087.0   314002.0
...             ...        ...
충청남도 금산군    27054.0    54612.0
     논산시    61489.0   123213.0
     당진시    79242.0   166630.0
     동남구   127784.0   258919.0
     보령시    51352.0   103873.0
     부여군    35350.0    70187.0
     서북구   176049.0   359036.0
     서산시    83018.0   170788.0
     서천군    28473.0    56012.0
     아산시   147237.0   302929.0
     예산군    40512.0    81339.0
     천안시   303833.0   617955.0
     청양군    16364.0    32753.0
     태안군    31640.0    63900.0
     홍성군    50202.0    99971.0
충청북도 괴산군    19200.0    38973.0
     단양군    15141.0    30503.0
     보은군    17128.0    34221.0
     상당구    86897.0   173701.0
     서원구   109254.0   217120.0
     영동군    25304.0    50552.0
     옥천군    26016.0    52267.0
     음성군    46415.0    97787.0
     제천시    68073.0   136517.0
     증평군    18198.0    37308.0
     진천군    33563.0    69950.0
     청원구    93807.0   190813.0
     청주시   415874.0   835197.0
     충주시   103473.0   208350.0
     흥덕구   125916.0   253563.0

[264 rows x 9 columns]

In [19]:
pd.pivot_table(population,index=['광역시도', '시도'],columns=['인구수','20 - 39세', '노인']).to_csv("../data/test2.csv")

In [20]:
pop_pivot.columns

MultiIndex(levels=[['20 - 39세', '노인', '인구수'], ['남자', '여자', '총인구']],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
           names=[None, '구분'])

In [21]:
pop_pivot['인구소멸비율'] = pop_pivot['20 - 39세','여자'] / (pop_pivot['노인','총인구']/2)

In [22]:
pop_pivot

           20 - 39세                           노인                          인구수  \
구분               남자        여자       총인구       남자       여자       총인구        남자
광역시도 시도
강원도  강릉시    26286.0   23098.0   49384.0  15767.0  21912.0   37679.0  106231.0
     고성군     4494.0    2529.0    7023.0   2900.0   4251.0    7151.0   15899.0
     동해시    11511.0    9753.0   21264.0   6392.0   8732.0   15124.0   47166.0
     삼척시     8708.0    7115.0   15823.0   5892.0   8718.0   14610.0   35253.0
     속초시     9956.0    8752.0   18708.0   5139.0   7613.0   12752.0   40288.0
     양구군     4368.0    2481.0    6849.0   1650.0   2458.0    4108.0   12918.0
     양양군     2916.0    2171.0    5087.0   2988.0   3993.0    6981.0   13838.0
     영월군     4025.0    3134.0    7159.0   4215.0   5700.0    9915.0   20652.0
     원주시    45755.0   43164.0   88919.0  17384.0  24862.0   42246.0  167854.0
     인제군     5512.0    3449.0    8961.0   2413.0   3189.0    5602.0   17677.0
     정선군     4138.0    3297.0    7435.0   3831.0   5177.0    9008.0   19975.0
     철원군     7918.0    4714.0   12632.0   3804.0   5308.0    9112.0   25429.0
     춘천시    37173.0   35422.0   72595.0  17259.0  24440.0   41699.0  138251.0
     태백시     5333.0    4643.0    9976.0   3978.0   5288.0    9266.0   23899.0
     평창군     4377.0    3585.0    7962.0   4223.0   5614.0    9837.0   22126.0
     홍천군     7900.0    6258.0   14158.0   6450.0   8483.0   14933.0   35738.0
     화천군     5397.0    2643.0    8040.0   1991.0   2815.0    4806.0   14554.0
     횡성군     4512.0    3789.0    8301.0   4941.0   6382.0   11323.0   23398.0
경기도  가평군     7024.0    5771.0   12795.0   5960.0   7609.0   13569.0   31981.0
     고양시   143723.0  145020.0  288743.0  46866.0  67226.0  114092.0  510923.0
     과천시     8582.0    8315.0   16897.0   3117.0   4618.0    7735.0   31013.0
     광명시    49509.0   47807.0   97316.0  15468.0  21081.0   36549.0  168241.0
     광주시    49690.0   45073.0   94763.0  16061.0  19142.0   35203.0  168345.0
     구리시    27732.0   26941.0   54673.0   8903.0  11720.0   20623.0   96397.0
     군포시    43183.0   41049.0   84232.0  12126.0  16404.0   28530.0  141647.0
     권선구    60291.0   56279.0  116570.0  13234.0  17690.0   30924.0  180766.0
     기흥구    56866.0   58658.0  115524.0  18831.0  24001.0   42832.0  206316.0
     김포시    49921.0   49660.0   99581.0  17847.0  22658.0   40505.0  182597.0
     남양주시   87416.0   86835.0  174251.0  33150.0  42836.0   75986.0  330749.0
     단원구    49620.0   43619.0   93239.0  10430.0  14100.0   24530.0  161915.0
...             ...       ...       ...      ...      ...       ...       ...
충청남도 금산군     5448.0    4454.0    9902.0   6012.0   8594.0   14606.0   27558.0
     논산시    14111.0   11900.0   26011.0  11593.0  16464.0   28057.0   61724.0
     당진시    24970.0   19356.0   44326.0  11765.0  15680.0   27445.0   87388.0
     동남구    38023.0   35222.0   73245.0  12858.0  17329.0   30187.0  131135.0
     보령시    12314.0    9590.0   21904.0   9579.0  13389.0   22968.0   52521.0
     부여군     6822.0    5348.0   12170.0   8575.0  12197.0   20772.0   34837.0
     서북구    63523.0   57966.0  121489.0  11150.0  15664.0   26814.0  182987.0
     서산시    23700.0   19196.0   42896.0  11840.0  16190.0   28030.0   87770.0
     서천군     5219.0    4142.0    9361.0   7221.0  10363.0   17584.0   27539.0
     아산시    47643.0   42296.0   89939.0  14581.0  20486.0   35067.0  155692.0
     예산군     8450.0    6665.0   15115.0   9230.0  12776.0   22006.0   40827.0
     천안시   101546.0   93188.0  194734.0  24008.0  32993.0   57001.0  314122.0
     청양군     3207.0    2410.0    5617.0   4300.0   6029.0   10329.0   16389.0
     태안군     6956.0    5271.0   12227.0   7241.0   9627.0   16868.0   32260.0
     홍성군    11691.0   10428.0   22119.0   8889.0  12426.0   21315.0   49769.0
충청북도 괴산군     3606.0    2726.0    6332.0   4890.0   6702.0   11592.0   19773.0
     단양군     2907.0    2289.0    5196.0   3278.0   4619.0    7897.0   15362.0
     보은군     3097.0    2498.0    5595.0   4165.0   6022.0   10187.0   17093.0
     상당구    23359.0   21071.0   44430.0   9727.0  13849.0   23576.0   86804.0
     서원구    31810.0   29168.0   60978.0   9950.0  14237.0   24187.0  107866.0
     영동군     5369.0    4217.0    9586.0   5564.0   8186.0   13750.0   25248.0
     옥천군     5373.0    4445.0    9818.0   5533.0   7722.0   13255.0   26251.0
     음성군    12684.0   10179.0   22863.0   7301.0   9605.0   16906.0   51372.0
     제천시    16563.0   14279.0   30842.0  10227.0  13904.0   24131.0   68444.0
     증평군     5531.0    4554.0   10085.0   2206.0   3117.0    5323.0   19110.0
     진천군     9391.0    7622.0   17013.0   4731.0   6575.0   11306.0   36387.0
     청원구    32216.0   27805.0   60021.0   8417.0  11914.0   20331.0   97006.0
     청주시   128318.0  115719.0  244037.0  37882.0  53671.0   91553.0  419323.0
     충주시    26600.0   22757.0   49357.0  14407.0  20383.0   34790.0  104877.0
     흥덕구    40933.0   37675.0   78608.0   9788.0  13671.0   23459.0  127647.0

                                  인구소멸비율
구분               여자        총인구
광역시도 시도
강원도  강릉시   107615.0   213846.0  1.226041
     고성군    14215.0    30114.0  0.707314
     동해시    46131.0    93297.0  1.289738
     삼척시    34346.0    69599.0  0.973990
     속초시    41505.0    81793.0  1.372647
     양구군    11092.0    24010.0  1.207887
     양양군    13380.0    27218.0  0.621974
     영월군    19421.0    40073.0  0.632173
     원주시   170125.0   337979.0  2.043460
     인제군    15043.0    32720.0  1.231346
     정선군    18743.0    38718.0  0.732016
     철원군    22584.0    48013.0  1.034680
     춘천시   142456.0   280707.0  1.698938
     태백시    23171.0    47070.0  1.002158
     평창군    21192.0    43318.0  0.728881
     홍천군    34338.0    70076.0  0.838144
     화천군    11710.0    26264.0  1.099875
     횡성군    22593.0    45991.0  0.669257
경기도  가평군    30467.0    62448.0  0.850615
     고양시   528761.0  1039684.0  2.542159
     과천시    32765.0    63778.0  2.149968
     광명시   171243.0   339484.0  2.616050
     광주시   159378.0   327723.0  2.560748
     구리시    97366.0   193763.0  2.612714
     군포시   143243.0   284890.0  2.877603
     권선구   177627.0   358393.0  3.639827
     기흥구   210847.0   417163.0  2.738980
     김포시   180846.0   363443.0  2.452043
     남양주시  331405.0   662154.0  2.285553
     단원구   152087.0   314002.0  3.556380
...             ...        ...       ...
충청남도 금산군    27054.0    54612.0  0.609886
     논산시    61489.0   123213.0  0.848273
     당진시    79242.0   166630.0  1.410530
     동남구   127784.0   258919.0  2.333587
     보령시    51352.0   103873.0  0.835075
     부여군    35350.0    70187.0  0.514924
     서북구   176049.0   359036.0  4.323562
     서산시    83018.0   170788.0  1.369675
     서천군    28473.0    56012.0  0.471110
     아산시   147237.0   302929.0  2.412296
     예산군    40512.0    81339.0  0.605744
     천안시   303833.0   617955.0  3.269697
     청양군    16364.0    32753.0  0.466647
     태안군    31640.0    63900.0  0.624970
     홍성군    50202.0    99971.0  0.978466
충청북도 괴산군    19200.0    38973.0  0.470324
     단양군    15141.0    30503.0  0.579714
     보은군    17128.0    34221.0  0.490429
     상당구    86897.0   173701.0  1.787496
     서원구   109254.0   217120.0  2.411874
     영동군    25304.0    50552.0  0.613382
     옥천군    26016.0    52267.0  0.670690
     음성군    46415.0    97787.0  1.204188
     제천시    68073.0   136517.0  1.183457
     증평군    18198.0    37308.0  1.711065
     진천군    33563.0    69950.0  1.348311
     청원구    93807.0   190813.0  2.735232
     청주시   415874.0   835197.0  2.527913
     충주시   103473.0   208350.0  1.308249
     흥덕구   125916.0   253563.0  3.211987

[264 rows x 10 columns]

In [23]:
pop_pivot['인구소멸지역'] = pop_pivot['인구소멸비율'] < 1

In [24]:
pop_pivot

           20 - 39세                           노인                          인구수  \
구분               남자        여자       총인구       남자       여자       총인구        남자
광역시도 시도
강원도  강릉시    26286.0   23098.0   49384.0  15767.0  21912.0   37679.0  106231.0
     고성군     4494.0    2529.0    7023.0   2900.0   4251.0    7151.0   15899.0
     동해시    11511.0    9753.0   21264.0   6392.0   8732.0   15124.0   47166.0
     삼척시     8708.0    7115.0   15823.0   5892.0   8718.0   14610.0   35253.0
     속초시     9956.0    8752.0   18708.0   5139.0   7613.0   12752.0   40288.0
     양구군     4368.0    2481.0    6849.0   1650.0   2458.0    4108.0   12918.0
     양양군     2916.0    2171.0    5087.0   2988.0   3993.0    6981.0   13838.0
     영월군     4025.0    3134.0    7159.0   4215.0   5700.0    9915.0   20652.0
     원주시    45755.0   43164.0   88919.0  17384.0  24862.0   42246.0  167854.0
     인제군     5512.0    3449.0    8961.0   2413.0   3189.0    5602.0   17677.0
     정선군     4138.0    3297.0    7435.0   3831.0   5177.0    9008.0   19975.0
     철원군     7918.0    4714.0   12632.0   3804.0   5308.0    9112.0   25429.0
     춘천시    37173.0   35422.0   72595.0  17259.0  24440.0   41699.0  138251.0
     태백시     5333.0    4643.0    9976.0   3978.0   5288.0    9266.0   23899.0
     평창군     4377.0    3585.0    7962.0   4223.0   5614.0    9837.0   22126.0
     홍천군     7900.0    6258.0   14158.0   6450.0   8483.0   14933.0   35738.0
     화천군     5397.0    2643.0    8040.0   1991.0   2815.0    4806.0   14554.0
     횡성군     4512.0    3789.0    8301.0   4941.0   6382.0   11323.0   23398.0
경기도  가평군     7024.0    5771.0   12795.0   5960.0   7609.0   13569.0   31981.0
     고양시   143723.0  145020.0  288743.0  46866.0  67226.0  114092.0  510923.0
     과천시     8582.0    8315.0   16897.0   3117.0   4618.0    7735.0   31013.0
     광명시    49509.0   47807.0   97316.0  15468.0  21081.0   36549.0  168241.0
     광주시    49690.0   45073.0   94763.0  16061.0  19142.0   35203.0  168345.0
     구리시    27732.0   26941.0   54673.0   8903.0  11720.0   20623.0   96397.0
     군포시    43183.0   41049.0   84232.0  12126.0  16404.0   28530.0  141647.0
     권선구    60291.0   56279.0  116570.0  13234.0  17690.0   30924.0  180766.0
     기흥구    56866.0   58658.0  115524.0  18831.0  24001.0   42832.0  206316.0
     김포시    49921.0   49660.0   99581.0  17847.0  22658.0   40505.0  182597.0
     남양주시   87416.0   86835.0  174251.0  33150.0  42836.0   75986.0  330749.0
     단원구    49620.0   43619.0   93239.0  10430.0  14100.0   24530.0  161915.0
...             ...       ...       ...      ...      ...       ...       ...
충청남도 금산군     5448.0    4454.0    9902.0   6012.0   8594.0   14606.0   27558.0
     논산시    14111.0   11900.0   26011.0  11593.0  16464.0   28057.0   61724.0
     당진시    24970.0   19356.0   44326.0  11765.0  15680.0   27445.0   87388.0
     동남구    38023.0   35222.0   73245.0  12858.0  17329.0   30187.0  131135.0
     보령시    12314.0    9590.0   21904.0   9579.0  13389.0   22968.0   52521.0
     부여군     6822.0    5348.0   12170.0   8575.0  12197.0   20772.0   34837.0
     서북구    63523.0   57966.0  121489.0  11150.0  15664.0   26814.0  182987.0
     서산시    23700.0   19196.0   42896.0  11840.0  16190.0   28030.0   87770.0
     서천군     5219.0    4142.0    9361.0   7221.0  10363.0   17584.0   27539.0
     아산시    47643.0   42296.0   89939.0  14581.0  20486.0   35067.0  155692.0
     예산군     8450.0    6665.0   15115.0   9230.0  12776.0   22006.0   40827.0
     천안시   101546.0   93188.0  194734.0  24008.0  32993.0   57001.0  314122.0
     청양군     3207.0    2410.0    5617.0   4300.0   6029.0   10329.0   16389.0
     태안군     6956.0    5271.0   12227.0   7241.0   9627.0   16868.0   32260.0
     홍성군    11691.0   10428.0   22119.0   8889.0  12426.0   21315.0   49769.0
충청북도 괴산군     3606.0    2726.0    6332.0   4890.0   6702.0   11592.0   19773.0
     단양군     2907.0    2289.0    5196.0   3278.0   4619.0    7897.0   15362.0
     보은군     3097.0    2498.0    5595.0   4165.0   6022.0   10187.0   17093.0
     상당구    23359.0   21071.0   44430.0   9727.0  13849.0   23576.0   86804.0
     서원구    31810.0   29168.0   60978.0   9950.0  14237.0   24187.0  107866.0
     영동군     5369.0    4217.0    9586.0   5564.0   8186.0   13750.0   25248.0
     옥천군     5373.0    4445.0    9818.0   5533.0   7722.0   13255.0   26251.0
     음성군    12684.0   10179.0   22863.0   7301.0   9605.0   16906.0   51372.0
     제천시    16563.0   14279.0   30842.0  10227.0  13904.0   24131.0   68444.0
     증평군     5531.0    4554.0   10085.0   2206.0   3117.0    5323.0   19110.0
     진천군     9391.0    7622.0   17013.0   4731.0   6575.0   11306.0   36387.0
     청원구    32216.0   27805.0   60021.0   8417.0  11914.0   20331.0   97006.0
     청주시   128318.0  115719.0  244037.0  37882.0  53671.0   91553.0  419323.0
     충주시    26600.0   22757.0   49357.0  14407.0  20383.0   34790.0  104877.0
     흥덕구    40933.0   37675.0   78608.0   9788.0  13671.0   23459.0  127647.0

                                  인구소멸비율 인구소멸지역
구분               여자        총인구
광역시도 시도
강원도  강릉시   107615.0   213846.0  1.226041  False
     고성군    14215.0    30114.0  0.707314   True
     동해시    46131.0    93297.0  1.289738  False
     삼척시    34346.0    69599.0  0.973990   True
     속초시    41505.0    81793.0  1.372647  False
     양구군    11092.0    24010.0  1.207887  False
     양양군    13380.0    27218.0  0.621974   True
     영월군    19421.0    40073.0  0.632173   True
     원주시   170125.0   337979.0  2.043460  False
     인제군    15043.0    32720.0  1.231346  False
     정선군    18743.0    38718.0  0.732016   True
     철원군    22584.0    48013.0  1.034680  False
     춘천시   142456.0   280707.0  1.698938  False
     태백시    23171.0    47070.0  1.002158  False
     평창군    21192.0    43318.0  0.728881   True
     홍천군    34338.0    70076.0  0.838144   True
     화천군    11710.0    26264.0  1.099875  False
     횡성군    22593.0    45991.0  0.669257   True
경기도  가평군    30467.0    62448.0  0.850615   True
     고양시   528761.0  1039684.0  2.542159  False
     과천시    32765.0    63778.0  2.149968  False
     광명시   171243.0   339484.0  2.616050  False
     광주시   159378.0   327723.0  2.560748  False
     구리시    97366.0   193763.0  2.612714  False
     군포시   143243.0   284890.0  2.877603  False
     권선구   177627.0   358393.0  3.639827  False
     기흥구   210847.0   417163.0  2.738980  False
     김포시   180846.0   363443.0  2.452043  False
     남양주시  331405.0   662154.0  2.285553  False
     단원구   152087.0   314002.0  3.556380  False
...             ...        ...       ...    ...
충청남도 금산군    27054.0    54612.0  0.609886   True
     논산시    61489.0   123213.0  0.848273   True
     당진시    79242.0   166630.0  1.410530  False
     동남구   127784.0   258919.0  2.333587  False
     보령시    51352.0   103873.0  0.835075   True
     부여군    35350.0    70187.0  0.514924   True
     서북구   176049.0   359036.0  4.323562  False
     서산시    83018.0   170788.0  1.369675  False
     서천군    28473.0    56012.0  0.471110   True
     아산시   147237.0   302929.0  2.412296  False
     예산군    40512.0    81339.0  0.605744   True
     천안시   303833.0   617955.0  3.269697  False
     청양군    16364.0    32753.0  0.466647   True
     태안군    31640.0    63900.0  0.624970   True
     홍성군    50202.0    99971.0  0.978466   True
충청북도 괴산군    19200.0    38973.0  0.470324   True
     단양군    15141.0    30503.0  0.579714   True
     보은군    17128.0    34221.0  0.490429   True
     상당구    86897.0   173701.0  1.787496  False
     서원구   109254.0   217120.0  2.411874  False
     영동군    25304.0    50552.0  0.613382   True
     옥천군    26016.0    52267.0  0.670690   True
     음성군    46415.0    97787.0  1.204188  False
     제천시    68073.0   136517.0  1.183457  False
     증평군    18198.0    37308.0  1.711065  False
     진천군    33563.0    69950.0  1.348311  False
     청원구    93807.0   190813.0  2.735232  False
     청주시   415874.0   835197.0  2.527913  False
     충주시   103473.0   208350.0  1.308249  False
     흥덕구   125916.0   253563.0  3.211987  False

[264 rows x 11 columns]

In [25]:
tmp = pop_pivot[pop_pivot['인구소멸지역'] == True].index.get_level_values(1)
tmp

Index(['고성군', '삼척시', '양양군', '영월군', '정선군', '평창군', '홍천군', '횡성군', '가평군', '양평군',
       '연천군', '거창군', '고성군', '남해군', '밀양시', '산청군', '의령군', '창녕군', '하동군', '함안군',
       '함양군', '합천군', '고령군', '군위군', '문경시', '봉화군', '상주시', '성주군', '영덕군', '영양군',
       '영주시', '영천시', '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '동구', '영도구',
       '강화군', '옹진군', '강진군', '고흥군', '곡성군', '구례군', '담양군', '보성군', '신안군', '영광군',
       '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군', '해남군', '화순군', '고창군', '김제시',
       '남원시', '무주군', '부안군', '순창군', '임실군', '장수군', '정읍시', '진안군', '공주시', '금산군',
       '논산시', '보령시', '부여군', '서천군', '예산군', '청양군', '태안군', '홍성군', '괴산군', '단양군',
       '보은군', '영동군', '옥천군'],
      dtype='object', name='시도')

In [26]:
len(tmp)

83

In [27]:
pop_pivot.columns.get_level_values(0)

Index(['20 - 39세', '20 - 39세', '20 - 39세', '노인', '노인', '노인', '인구수', '인구수',
       '인구수', '인구소멸비율', '인구소멸지역'],
      dtype='object')

In [28]:
pop_pivot.columns = pop_pivot.columns.get_level_values(0) + pop_pivot.columns.get_level_values(1)

In [29]:
pop_pivot.reset_index(inplace=True)

In [30]:
pop_pivot[pop_pivot['광역시도'] == '경기도']

,광역시도,시도,20 - 39세남자,20 - 39세여자,20 - 39세총인구,노인남자,노인여자,노인총인구,인구수남자,인구수여자,인구수총인구,인구소멸비율,인구소멸지역
18,경기도,가평군,7024.0,5771.000000,12795.000000,5960.000000,7609.0,13569.000000,31981.000000,30467.0,6.244800e+04,0.850615,True
19,경기도,고양시,143723.0,145020.000000,288743.000000,46866.000000,67226.0,114092.000000,510923.000000,528761.0,1.039684e+06,2.542159,False
20,경기도,과천시,8582.0,8315.000000,16897.000000,3117.000000,4618.0,7735.000000,31013.000000,32765.0,6.377800e+04,2.149968,False
21,경기도,광명시,49509.0,47807.000000,97316.000000,15468.000000,21081.0,36549.000000,168241.000000,171243.0,3.394840e+05,2.616050,False
22,경기도,광주시,49690.0,45073.000000,94763.000000,16061.000000,19142.0,35203.000000,168345.000000,159378.0,3.277230e+05,2.560748,False
23,경기도,구리시,27732.0,26941.000000,54673.000000,8903.000000,11720.0,20623.000000,96397.000000,97366.0,1.937630e+05,2.612714,False
24,경기도,군포시,43183.0,41049.000000,84232.000000,12126.000000,16404.0,28530.000000,141647.000000,143243.0,2.848900e+05,2.877603,False
25,경기도,권선구,60291.0,56279.000000,116570.000000,13234.000000,17690.0,30924.000000,180766.000000,177627.0,3.583930e+05,3.639827,False
26,경기도,기흥구,56866.0,58658.000000,115524.000000,18831.000000,24001.0,42832.000000,206316.000000,210847.0,4.171630e+05,2.738980,False
27,경기도,김포시,49921.0,49660.000000,99581.000000,17847.000000,22658.0,40505.000000,182597.000000,180846.0,3.634430e+05,2.452043,False
28,경기도,남양주시,87416.0,86835.000000,174251.000000,33150.000000,42836.0,75986.000000,330749.000000,331405.0,6.621540e+05,2.285553,False
29,경기도,단원구,49620.0,43619.000000,93239.000000,10430.000000,14100.0,24530.000000,161915.000000,152087.0,3.140020e+05,3.556380,False
30,경기도,덕양구,63137.0,61556.000000,124693.000000,22587.000000,31825.0,54412.000000,221496.000000,224737.0,4.462330e+05,2.262589,False
31,경기도,동두천시,12567.0,11634.000000,24201.000000,6591.000000,9581.0,16172.000000,48970.000000,49307.0,9.827700e+04,1.438783,False
32,경기도,동안구,51246.0,49730.000000,100976.000000,13092.000000,18279.0,31371.000000,170166.000000,174895.0,3.450610e+05,3.170444,False
33,경기도,만안구,39518.0,36093.000000,75611.000000,13369.000000,16935.0,30304.000000,126793.000000,125560.0,2.523530e+05,2.382062,False
34,경기도,부천시,133053.0,125233.000000,258286.000000,37075.000000,49143.0,86218.000000,425101.000000,426279.0,8.513800e+05,2.905031,False
35,경기도,분당구,72407.0,77174.000000,149581.000000,21745.000000,29118.0,50863.000000,244502.000000,259328.0,5.038300e+05,3.034583,False
36,경기도,상록구,60302.0,53671.000000,113973.000000,13411.000000,19209.0,32620.000000,191479.000000,184378.0,3.758570e+05,3.290681,False
37,경기도,성남시,147646.0,144389.000000,292035.000000,47327.000000,62417.0,109744.000000,483374.000000,491206.0,9.745800e+05,2.631378,False
38,경기도,소사구,44351.0,41744.333333,86095.333333,12358.333333,16381.0,28739.333333,141700.333333,142093.0,2.837933e+05,2.905031,False
39,경기도,수원시,197479.0,183461.000000,380940.000000,43757.000000,60235.0,103992.000000,601152.000000,592889.0,1.194041e+06,3.528368,False
40,경기도,수정구,37737.0,33210.000000,70947.000000,13013.000000,17065.0,30078.000000,118343.000000,114498.0,2.328410e+05,2.208259,False
41,경기도,수지구,44601.0,47997.000000,92598.000000,17133.000000,21255.0,38388.000000,170217.000000,177616.0,3.478330e+05,2.500625,False
42,경기도,시흥시,62869.0,53502.000000,116371.000000,13266.000000,18384.0,31650.000000,211392.000000,191496.0,4.028880e+05,3.380853,False
43,경기도,안산시,109922.0,97290.000000,207212.000000,23841.000000,33309.0,57150.000000,353394.000000,336465.0,6.898590e+05,3.404724,False
44,경기도,안성시,25450.0,22206.000000,47656.000000,11184.000000,15422.0,26606.000000,93389.000000,89507.0,1.828960e+05,1.669248,False
45,경기도,안양시,90764.0,85823.000000,176587.000000,26461.000000,35214.0,61675.000000,296959.000000,300455.0,5.974140e+05,2.783073,False
46,경기도,양주시,26137.0,24392.000000,50529.000000,11807.000000,14901.0,26708.000000,104235.000000,101278.0,2.055130e+05,1.826569,False
47,경기도,양평군,11988.0,10611.000000,22599.000000,10579.000000,13035.0,23614.000000,56285.000000,55082.0,1.113670e+05,0.898704,True
48,경기도,여주시,13629.0,12220.000000,25849.000000,8605.000000,11173.0,19778.000000,56445.000000,55118.0,1.115630e+05,1.235716,False
49,경기도,연천군,6535.0,4411.000000,10946.000000,4348.000000,5814.0,10162.000000,24090.000000,21817.0,4.590700e+04,0.868136,True
50,경기도,영통구,59277.0,56425.000000,115702.000000,7783.000000,11359.0,19142.000000,171452.000000,169202.0,3.406540e+05,5.895413,False
51,경기도,오산시,35374.0,31887.000000,67261.000000,6777.000000,9238.0,16015.000000,107056.000000,101600.0,2.086560e+05,3.982142,False
52,경기도,오정구,44351.0,41744.333333,86095.333333,12358.333333,16381.0,28739.333333,141700.333333,142093.0,2.837933e+05,2.905031,False
53,경기도,용인시,134278.0,135898.000000,270176.000000,47956.000000,61012.0,108968.000000,492374.000000,498752.0,9.911260e+05,2.494274,False
54,경기도,원미구,44351.0,41744.333333,86095.333333,12358.333333,16381.0,28739.333333,141700.333333,142093.0,2.837933e+05,2.905031,False
55,경기도,의왕시,23325.0,21551.000000,44876.000000,7282.000000,9630.0,16912.000000,78304.000000,78459.0,1.567630e+05,2.548605,False
56,경기도,의정부시,60876.0,58697.000000,119573.000000,23444.000000,31952.0,55396.000000,216400.000000,222057.0,4.384570e+05,2.119178,False
57,경기도,이천시,30551.0,28026.000000,58577.000000,10891.000000,14489.0,25380.000000,107044.000000,103315.0,2.103590e+05,2.208511,False
58,경기도,일산동구,41129.0,42571.000000,83700.000000,11972.000000,17244.0,29216.000000,142947.000000,149665.0,2.926120e+05,2.914225,False
59,경기도,일산서구,39457.0,40893.000000,80350.000000,12307.000000,18157.0,30464.000000,146480.000000,154359.0,3.008390e+05,2.684677,False
60,경기도,장안구,45738.0,41481.000000,87219.000000,12574.000000,17542.0,30116.000000,148987.000000,147492.0,2.964790e+05,2.754748,False
61,경기도,중원구,37502.0,34005.000000,71507.000000,12569.000000,16234.0,28803.000000,120529.000000,117380.0,2.379090e+05,2.361212,False
62,경기도,처인구,32811.0,29243.000000,62054.000000,11992.000000,15756.0,27748.000000,115841.000000,110289.0,2.261300e+05,2.107756,False
63,경기도,파주시,63159.0,57352.000000,120511.000000,22005.000000,29975.0,51980.000000,218565.000000,212216.0,4.307810e+05,2.206695,False
64,경기도,팔달구,32173.0,29276.000000,61449.000000,10166.000000,13644.0,23810.000000,99947.000000,98568.0,1.985150e+05,2.459135,False
65,경기도,평택시,71373.0,62672.000000,134045.000000,22148.000000,30942.0,53090.000000,240345.000000,230487.0,4.708320e+05,2.360972,False
66,경기도,포천시,19970.0,16384.000000,36354.000000,10528.000000,13764.0,24292.000000,81291.000000,73472.0,1.547630e+05,1.348921,False
67,경기도,하남시,31639.0,30193.000000,61832.000000,10622.000000,12684.0,23306.000000,106472.000000,104629.0,2.111010e+05,2.591007,False
68,경기도,화성시,100301.0,93228.000000,193529.000000,22896.000000,29979.0,52875.000000,330923.000000,309967.0,6.408900e+05,3.526355,False

In [31]:
with open("../data/05. skorea_municipalities_geo_simple.json", encoding='utf-8') as j:
    geo_data  = json.load(j)

In [32]:
map_korea = folium.Map(location=[37.484206, 126.782125], zoom_start=11.5, tiles = 'Stamen Toner')

In [33]:
map_korea

In [34]:
glob('../data/05.*')

['../data/05. draw_korea_raw.xlsx',
 '../data/05. draw_korea.csv',
 '../data/05. population_raw_data.xlsx',
 '../data/05. election_result.csv',
 '../data/05. skorea_municipalities_geo_simple.json']

In [35]:
pop_pivot['광역시도'].unique()

array(['강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '부산광역시',
       '서울특별시', '세종특별자치시', '울산광역시', '인천광역시', '전라남도', '전라북도', '제주특별자치도',
       '충청남도', '충청북도'], dtype=object)

In [36]:
pop_pivot['시도']

0       강릉시
1       고성군
2       동해시
3       삼척시
4       속초시
5       양구군
6       양양군
7       영월군
8       원주시
9       인제군
10      정선군
11      철원군
12      춘천시
13      태백시
14      평창군
15      홍천군
16      화천군
17      횡성군
18      가평군
19      고양시
20      과천시
21      광명시
22      광주시
23      구리시
24      군포시
25      권선구
26      기흥구
27      김포시
28     남양주시
29      단원구
       ...
234     금산군
235     논산시
236     당진시
237     동남구
238     보령시
239     부여군
240     서북구
241     서산시
242     서천군
243     아산시
244     예산군
245     천안시
246     청양군
247     태안군
248     홍성군
249     괴산군
250     단양군
251     보은군
252     상당구
253     서원구
254     영동군
255     옥천군
256     음성군
257     제천시
258     증평군
259     진천군
260     청원구
261     청주시
262     충주시
263     흥덕구
Name: 시도, Length: 264, dtype: object

In [37]:
len(pop_pivot['시도'])

264

In [38]:
pop_pivot['시도'].unique()

array(['강릉시', '고성군', '동해시', '삼척시', '속초시', '양구군', '양양군', '영월군', '원주시',
       '인제군', '정선군', '철원군', '춘천시', '태백시', '평창군', '홍천군', '화천군', '횡성군',
       '가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '권선구', '기흥구',
       '김포시', '남양주시', '단원구', '덕양구', '동두천시', '동안구', '만안구', '부천시', '분당구',
       '상록구', '성남시', '소사구', '수원시', '수정구', '수지구', '시흥시', '안산시', '안성시',
       '안양시', '양주시', '양평군', '여주시', '연천군', '영통구', '오산시', '오정구', '용인시',
       '원미구', '의왕시', '의정부시', '이천시', '일산동구', '일산서구', '장안구', '중원구', '처인구',
       '파주시', '팔달구', '평택시', '포천시', '하남시', '화성시', '거제시', '거창군', '김해시',
       '남해군', '마산합포구', '마산회원구', '밀양시', '사천시', '산청군', '성산구', '양산시', '의령군',
       '의창구', '진주시', '진해구', '창녕군', '창원시', '통영시', '하동군', '함안군', '함양군',
       '합천군', '경산시', '경주시', '고령군', '구미시', '군위군', '김천시', '남구', '문경시',
       '봉화군', '북구', '상주시', '성주군', '안동시', '영덕군', '영양군', '영주시', '영천시',
       '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '칠곡군', '포항시', '광산구',
       '동구', '서구', '달서구', '달성군', '수성구', '중구', '대덕구', '유성구', '강서구', '금정구',
       '기장군', '동래구', '부산진구', '사상구', '사하구', '수영구', '연제구', '영도구', '해운대구',
       '강남구', '강동구', '강북구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구',
       '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구',
       '영등포구', '용산구', '은평구', '종로구', '중랑구', '세종특별자치시', '울주군', '강화군', '계양구',
       '남동구', '부평구', '연수구', '옹진군', '강진군', '고흥군', '곡성군', '광양시', '구례군',
       '나주시', '담양군', '목포시', '무안군', '보성군', '순천시', '신안군', '여수시', '영광군',
       '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군', '해남군', '화순군', '고창군',
       '군산시', '김제시', '남원시', '덕진구', '무주군', '부안군', '순창군', '완산구', '완주군',
       '익산시', '임실군', '장수군', '전주시', '정읍시', '진안군', '서귀포시', '제주시', '계룡시',
       '공주시', '금산군', '논산시', '당진시', '동남구', '보령시', '부여군', '서북구', '서산시',
       '서천군', '아산시', '예산군', '천안시', '청양군', '태안군', '홍성군', '괴산군', '단양군',
       '보은군', '상당구', '서원구', '영동군', '옥천군', '음성군', '제천시', '증평군', '진천군',
       '청원구', '청주시', '충주시', '흥덕구'], dtype=object)

In [39]:
len(pop_pivot['시도'].unique())

239

In [40]:
tmp_gu_dict = {'수원':['장안구', '권선구', '팔달구', '영통구'], 
                       '성남':['수정구', '중원구', '분당구'], 
                       '안양':['만안구', '동안구'], 
                       '안산':['상록구', '단원구'], 
                       '고양':['덕양구', '일산동구', '일산서구'], 
                       '용인':['처인구', '기흥구', '수지구'], 
                       '청주':['상당구', '서원구', '흥덕구', '청원구'], 
                       '천안':['동남구', '서북구'], 
                       '전주':['완산구', '덕진구'], 
                       '포항':['남구', '북구'], 
                       '창원':['의창구', '성산구', '진해구', '마산합포구', '마산회원구'], 
                       '부천':['오정구', '원미구', '소사구']}

In [41]:
pop_pivot

,광역시도,시도,20 - 39세남자,20 - 39세여자,20 - 39세총인구,노인남자,노인여자,노인총인구,인구수남자,인구수여자,인구수총인구,인구소멸비율,인구소멸지역
0,강원도,강릉시,26286.0,23098.0,49384.0,15767.0,21912.0,37679.0,106231.0,107615.0,213846.0,1.226041,False
1,강원도,고성군,4494.0,2529.0,7023.0,2900.0,4251.0,7151.0,15899.0,14215.0,30114.0,0.707314,True
2,강원도,동해시,11511.0,9753.0,21264.0,6392.0,8732.0,15124.0,47166.0,46131.0,93297.0,1.289738,False
3,강원도,삼척시,8708.0,7115.0,15823.0,5892.0,8718.0,14610.0,35253.0,34346.0,69599.0,0.973990,True
4,강원도,속초시,9956.0,8752.0,18708.0,5139.0,7613.0,12752.0,40288.0,41505.0,81793.0,1.372647,False
5,강원도,양구군,4368.0,2481.0,6849.0,1650.0,2458.0,4108.0,12918.0,11092.0,24010.0,1.207887,False
6,강원도,양양군,2916.0,2171.0,5087.0,2988.0,3993.0,6981.0,13838.0,13380.0,27218.0,0.621974,True
7,강원도,영월군,4025.0,3134.0,7159.0,4215.0,5700.0,9915.0,20652.0,19421.0,40073.0,0.632173,True
8,강원도,원주시,45755.0,43164.0,88919.0,17384.0,24862.0,42246.0,167854.0,170125.0,337979.0,2.043460,False
9,강원도,인제군,5512.0,3449.0,8961.0,2413.0,3189.0,5602.0,17677.0,15043.0,32720.0,1.231346,False
10,강원도,정선군,4138.0,3297.0,7435.0,3831.0,5177.0,9008.0,19975.0,18743.0,38718.0,0.732016,True
11,강원도,철원군,7918.0,4714.0,12632.0,3804.0,5308.0,9112.0,25429.0,22584.0,48013.0,1.034680,False
12,강원도,춘천시,37173.0,35422.0,72595.0,17259.0,24440.0,41699.0,138251.0,142456.0,280707.0,1.698938,False
13,강원도,태백시,5333.0,4643.0,9976.0,3978.0,5288.0,9266.0,23899.0,23171.0,47070.0,1.002158,False
14,강원도,평창군,4377.0,3585.0,7962.0,4223.0,5614.0,9837.0,22126.0,21192.0,43318.0,0.728881,True
15,강원도,홍천군,7900.0,6258.0,14158.0,6450.0,8483.0,14933.0,35738.0,34338.0,70076.0,0.838144,True
16,강원도,화천군,5397.0,2643.0,8040.0,1991.0,2815.0,4806.0,14554.0,11710.0,26264.0,1.099875,False
17,강원도,횡성군,4512.0,3789.0,8301.0,4941.0,6382.0,11323.0,23398.0,22593.0,45991.0,0.669257,True
18,경기도,가평군,7024.0,5771.0,12795.0,5960.0,7609.0,13569.0,31981.0,30467.0,62448.0,0.850615,True
19,경기도,고양시,143723.0,145020.0,288743.0,46866.0,67226.0,114092.0,510923.0,528761.0,1039684.0,2.542159,False
20,경기도,과천시,8582.0,8315.0,16897.0,3117.0,4618.0,7735.0,31013.0,32765.0,63778.0,2.149968,False
21,경기도,광명시,49509.0,47807.0,97316.0,15468.0,21081.0,36549.0,168241.0,171243.0,339484.0,2.616050,False
22,경기도,광주시,49690.0,45073.0,94763.0,16061.0,19142.0,35203.0,168345.0,159378.0,327723.0,2.560748,False
23,경기도,구리시,27732.0,26941.0,54673.0,8903.0,11720.0,20623.0,96397.0,97366.0,193763.0,2.612714,False
24,경기도,군포시,43183.0,41049.0,84232.0,12126.0,16404.0,28530.0,141647.0,143243.0,284890.0,2.877603,False
25,경기도,권선구,60291.0,56279.0,116570.0,13234.0,17690.0,30924.0,180766.0,177627.0,358393.0,3.639827,False
26,경기도,기흥구,56866.0,58658.0,115524.0,18831.0,24001.0,42832.0,206316.0,210847.0,417163.0,2.738980,False
27,경기도,김포시,49921.0,49660.0,99581.0,17847.0,22658.0,40505.0,182597.0,180846.0,363443.0,2.452043,False
28,경기도,남양주시,87416.0,86835.0,174251.0,33150.0,42836.0,75986.0,330749.0,331405.0,662154.0,2.285553,False
29,경기도,단원구,49620.0,43619.0,93239.0,10430.0,14100.0,24530.0,161915.0,152087.0,314002.0,3.556380,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,충청남도,금산군,5448.0,4454.0,9902.0,6012.0,8594.0,14606.0,27558.0,27054.0,54612.0,0.609886,True
235,충청남도,논산시,14111.0,11900.0,26011.0,11593.0,16464.0,28057.0,61724.0,61489.0,123213.0,0.848273,True
236,충청남도,당진시,24970.0,19356.0,44326.0,11765.0,15680.0,27445.0,87388.0,79242.0,166630.0,1.410530,False
237,충청남도,동남구,38023.0,35222.0,73245.0,12858.0,17329.0,30187.0,131135.0,127784.0,258919.0,2.333587,False
238,충청남도,보령시,12314.0,9590.0,21904.0,9579.0,13389.0,22968.0,52521.0,51352.0,103873.0,0.835075,True
239,충청남도,부여군,6822.0,5348.0,12170.0,8575.0,12197.0,20772.0,34837.0,35350.0,70187.0,0.514924,True
240,충청남도,서북구,63523.0,57966.0,121489.0,11150.0,15664.0,26814.0,182987.0,176049.0,359036.0,4.323562,False
241,충청남도,서산시,23700.0,19196.0,42896.0,11840.0,16190.0,28030.0,87770.0,83018.0,170788.0,1.369675,False
242,충청남도,서천군,5219.0,4142.0,9361.0,7221.0,10363.0,17584.0,27539.0,28473.0,56012.0,0.471110,True
243,충청남도,아산시,47643.0,42296.0,89939.0,14581.0,20486.0,35067.0,155692.0,147237.0,302929.0,2.412296,False
244,충청남도,예산군,8450.0,6665.0,15115.0,9230.0,12776.0,22006.0,40827.0,40512.0,81339.0,0.605744,True
245,충청남도,천안시,101546.0,93188.0,194734.0,24008.0,32993.0,57001.0,314122.0,303833.0,617955.0,3.269697,False
246,충청남도,청양군,3207.0,2410.0,5617.0,4300.0,6029.0,10329.0,16389.0,16364.0,32753.0,0.466647,True
247,충청남도,태안군,6956.0,5271.0,12227.0,7241.0,9627.0,16868.0,32260.0,31640.0,63900.0,0.624970,True
248,충청남도,홍성군,11691.0,10428.0,22119.0,8889.0,12426.0,21315.0,49769.0,50202.0,99971.0,0.978466,True
249,충청북도,괴산군,3606.0,2726.0,6332.0,4890.0,6702.0,11592.0,19773.0,19200.0,38973.0,0.470324,True
250,충청북도,단양군,2907.0,2289.0,5196.0,3278.0,4619.0,7897.0,15362.0,15141.0,30503.0,0.579714,True
251,충청북도,보은군,3097.0,2498.0,5595.0,4165.0,6022.0,10187.0,17093.0,17128.0,34221.0,0.490429,True
252,충청북도,상당구,23359.0,21071.0,44430.0,9727.0,13849.0,23576.0,86804.0,86897.0,173701.0,1.787496,False
253,충청북도,서원구,31810.0,29168.0,60978.0,9950.0,14237.0,24187.0,107866.0,109254.0,217120.0,2.411874,False
254,충청북도,영동군,5369.0,4217.0,9586.0,5564.0,8186.0,13750.0,25248.0,25304.0,50552.0,0.613382,True
255,충청북도,옥천군,5373.0,4445.0,9818.0,5533.0,7722.0,13255.0,26251.0,26016.0,52267.0,0.670690,True
256,충청북도,음성군,12684.0,10179.0,22863.0,7301.0,9605.0,16906.0,51372.0,46415.0,97787.0,1.204188,False
257,충청북도,제천시,16563.0,14279.0,30842.0,10227.0,13904.0,24131.0,68444.0,68073.0,136517.0,1.183457,False
258,충청북도,증평군,5531.0,4554.0,10085.0,2206.0,3117.0,5323.0,19110.0,18198.0,37308.0,1.711065,False
259,충청북도,진천군,9391.0,7622.0,17013.0,4731.0,6575.0,11306.0,36387.0,33563.0,69950.0,1.348311,False
260,충청북도,청원구,32216.0,27805.0,60021.0,8417.0,11914.0,20331.0,97006.0,93807.0,190813.0,2.735232,False
261,충청북도,청주시,128318.0,115719.0,244037.0,37882.0,53671.0,91553.0,419323.0,415874.0,835197.0,2.527913,False
262,충청북도,충주시,26600.0,22757.0,49357.0,14407.0,20383.0,34790.0,104877.0,103473.0,208350.0,1.308249,False
263,충청북도,흥덕구,40933.0,37675.0,78608.0,9788.0,13671.0,23459.0,127647.0,125916.0,253563.0,3.211987,False

In [42]:
si_name = [None]*len(pop_pivot)

In [43]:
len(si_name)

264

In [44]:
pop_pivot.index

RangeIndex(start=0, stop=264, step=1)

In [45]:
for i in pop_pivot.index:
    
    if pop_pivot['광역시도'][i][-3:] not in ['광역시', '자치시', '특별시']:
        if pop_pivot['시도'][i][:-1] == '고성' and pop_pivot['광역시도'][i] == '강원도':
            si_name[i] = '고성(강원)'
        elif pop_pivot['시도'][i][:-1] == '고성' and pop_pivot['광역시도'][i] == '경상남도':
            si_name[i] = '고성(경남)'
        else:
            si_name[i] = pop_pivot['시도'][i][:-1]
        
        for keys, values in tmp_gu_dict.items():
            if pop_pivot['시도'][i] in values:
                if len(pop_pivot['시도'][i]) == 2:
                    si_name[i] = keys + ' ' + pop_pivot['시도'][i]
                elif pop_pivot['시도'][i] in ['마산합포구', '마산회원구']:
                    si_name[i] = keys + ' ' + pop_pivot['시도'][i][2:-1]
                else:
                    si_name[i] = keys + ' ' + pop_pivot['시도'][i][:-1]
                    
    elif pop_pivot['광역시도'][i] == '세종특별자치시':
            si_name[i] = '세종'
        
    else:
        if len(pop_pivot['시도'][i]) == 2:
            si_name[i] = pop_pivot['광역시도'][i][:2] + ' ' + pop_pivot['시도'][i]
        else:
            si_name[i] = pop_pivot['광역시도'][i][:2] + ' ' + pop_pivot['시도'][:-1]

In [46]:
tmp_gu_dict

{'수원': ['장안구', '권선구', '팔달구', '영통구'],
 '성남': ['수정구', '중원구', '분당구'],
 '안양': ['만안구', '동안구'],
 '안산': ['상록구', '단원구'],
 '고양': ['덕양구', '일산동구', '일산서구'],
 '용인': ['처인구', '기흥구', '수지구'],
 '청주': ['상당구', '서원구', '흥덕구', '청원구'],
 '천안': ['동남구', '서북구'],
 '전주': ['완산구', '덕진구'],
 '포항': ['남구', '북구'],
 '창원': ['의창구', '성산구', '진해구', '마산합포구', '마산회원구'],
 '부천': ['오정구', '원미구', '소사구']}

In [47]:
pop_pivot['ID'] = si_name

In [48]:
pop_pivot.to_csv("../data/temp_csv_delete.csv")